wandb_version: 1

n_epochs:
  desc: null
  value: 5000
max_ts:
  desc: null
  value: 1000
n_trials:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693734886.232075
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.15.9
      8:
      - 5
